# Generated by Django 6.0.4 on 2026-04-20 19:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('coach', 'Coach'), ('client', 'Client')], default='coach', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=10)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('pause', 'En pause'), ('inactif', 'Inactif'), ('nouveau', 'Nouveau')], default='nouveau', max_length=15)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('taille_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poids_depart_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('poids_cible_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('niveau', models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=15)),
                ('objectifs', models.JSONField(blank=True, default=list)),
                ('blessures', models.TextField(blank=True)),
                ('contraintes_medicales', models.TextField(blank=True)),
                ('disponibilites', models.JSONField(blank=True, default=list)),
                ('alimentation', models.CharField(blank=True, max_length=100)),
                ('tarif_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('parraine_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='core.client')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignationProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=15)),
                ('semaine_courante', models.PositiveSmallIntegerField(default=1)),
                ('notes_coach', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='core.client')),
            ],
            options={
                'db_table': 'assignations_programmes',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('absences', 'Absences'), ('inactivite', 'Inactivité'), ('facture_retard', 'Facture retard'), ('fin_programme', 'Fin programme'), ('objectif_atteint', 'Objectif atteint')], default='absences', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=10)),
                ('lue', models.BooleanField(default=False)),
                ('traitee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.client')),
            ],
            options={
                'db_table': 'alertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialites', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro')], default='free', max_length=10)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coach_profiles',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'unique_together': {('coach', 'client')},
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('retard', 'Retard'), ('annulee', 'Annulée')], default='brouillon', max_length=15)),
                ('lignes', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('nb_relances', models.PositiveSmallIntegerField(default=0)),
                ('derniere_relance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.assignationprogramme')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('expediteur_role', models.CharField(choices=[('coach', 'Coach'), ('client', 'Client')], max_length=10)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tour_taille_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tour_hanches_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tour_cuisse_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('masse_grasse_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='core.client')),
            ],
            options={
                'db_table': 'mesures',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('valeur_cible', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valeur_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('atteint', 'Atteint'), ('abandonne', 'Abandonné')], default='en_cours', max_length=15)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_atteint', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_list', to='core.client')),
            ],
            options={
                'db_table': 'objectifs',
            },
        ),
        migrations.CreateModel(
            name='PhotoProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients/progression/')),
                ('date', models.DateField()),
                ('angle', models.CharField(choices=[('face', 'Face'), ('profil', 'Profil'), ('dos', 'Dos')], default='face', max_length=10)),
                ('semaine_programme', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.client')),
            ],
            options={
                'db_table': 'photos_progression',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('force', 'Force & Musculation'), ('cardio', 'Cardio & Endurance'), ('perte_poids', 'Perte de poids'), ('remise_forme', 'Remise en forme'), ('mobilite', 'Mobilité & Souplesse'), ('custom', 'Personnalisé')], max_length=20)),
                ('duree_semaines', models.PositiveSmallIntegerField()),
                ('seances_par_semaine', models.PositiveSmallIntegerField()),
                ('modules', models.JSONField(blank=True, default=list)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('est_template', models.BooleanField(default=True)),
                ('genere_par_ia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programmes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu_html', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('signe', 'Signé'), ('expire', 'Expiré')], default='brouillon', max_length=10)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('signature_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('token_signature', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='core.client')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.programme')),
            ],
            options={
                'db_table': 'contrats',
            },
        ),
        migrations.AddField(
            model_name='assignationprogramme',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='core.programme'),
        ),
        migrations.CreateModel(
            name='QuestionnaireInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_sportive', models.TextField(blank=True)),
                ('sports_pratiques', models.JSONField(blank=True, default=list)),
                ('pathologies', models.TextField(blank=True)),
                ('medicaments', models.TextField(blank=True)),
                ('tabac', models.BooleanField(default=False)),
                ('alcool', models.CharField(blank=True, max_length=50)),
                ('sommeil_heures', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('stress_niveau', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('motivation_niveau', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('remarques', models.TextField(blank=True)),
                ('rempli_le', models.DateField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='core.client')),
            ],
            options={
                'db_table': 'questionnaires_initiaux',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('duree_minutes', models.PositiveSmallIntegerField(default=60)),
                ('type_seance', models.CharField(choices=[('presentiel', 'Présentiel'), ('visio', 'Visio'), ('autonome', 'Autonome')], default='presentiel', max_length=15)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('realisee', 'Réalisée'), ('annulee', 'Annulée'), ('absence', 'Absence')], default='planifiee', max_length=15)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('exercices', models.JSONField(blank=True, default=list)),
                ('notes_avant', models.TextField(blank=True)),
                ('notes_apres', models.TextField(blank=True)),
                ('rpe_client', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ressenti_client', models.TextField(blank=True)),
                ('semaine_numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.assignationprogramme')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_coach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seances',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='NoteSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('general', 'Général'), ('performance', 'Performance'), ('nutrition', 'Nutrition'), ('psychologie', 'Psychologie'), ('medical', 'Médical')], default='general', max_length=15)),
                ('visible_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.seance')),
            ],
            options={
                'db_table': 'notes_suivi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('relance', 'Relance absence'), ('felicitations', 'Félicitations'), ('rappel', 'Rappel séance'), ('bilan', 'Bilan programme'), ('renouvellement', 'Renouvellement'), ('facture', 'Relance facture'), ('custom', 'Personnalisé')], max_length=20)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'templates_messages',
            },
        ),
    ]
