# Generated by Django 6.0.5 on 2026-05-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('absences', 'Absences'), ('inactivite', 'Inactivité'), ('facture_retard', 'Facture retard'), ('fin_programme', 'Fin programme'), ('objectif_atteint', 'Objectif atteint'), ('nouvelle_mesure', 'Nouvelle mesure')], default='absences', max_length=20),
        ),
    ]
