# Generated by Django 6.0.5 on 2026-05-20 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_email_verified_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercice_nom', models.CharField(max_length=200)),
                ('serie_numero', models.PositiveSmallIntegerField(default=1)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('repetitions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duree_secondes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_log', to='core.seance')),
            ],
            options={
                'db_table': 'series_log',
                'ordering': ['created_at'],
            },
        ),
    ]
