# Generated by Django 6.0.5 on 2026-05-20 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_serie_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('viandes_poissons', 'Viandes & Poissons'), ('legumes', 'Légumes'), ('feculents', 'Féculents & Céréales'), ('laitiers', 'Produits laitiers'), ('fruits', 'Fruits'), ('matieres_grasses', 'Matières grasses'), ('legumineuses', 'Légumineuses'), ('autres', 'Autres')], default='autres', max_length=20)),
                ('calories_100g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('proteines_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('glucides_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('lipides_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fibres_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliments_custom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aliments',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PlanAlimentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objectif_calories', models.IntegerField(blank=True, null=True)),
                ('objectif_proteines_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('objectif_glucides_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('objectif_lipides_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_alimentaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plans_alimentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_alimentaires', to='core.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='core.planalimentaire')),
            ],
            options={
                'db_table': 'assignations_plans',
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('portions', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recettes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='JournalAlimentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type_repas', models.CharField(choices=[('petit_dejeuner', 'Petit-déjeuner'), ('collation_matin', 'Collation matin'), ('dejeuner', 'Déjeuner'), ('collation_soir', 'Collation après-midi'), ('diner', 'Dîner')], max_length=20)),
                ('quantite_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aliment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aliment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_alimentaire', to='core.client')),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recette')),
            ],
            options={
                'db_table': 'journal_alimentaire',
                'ordering': ['-date', 'type_repas'],
            },
        ),
        migrations.CreateModel(
            name='IngredientRecette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aliment')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.recette')),
            ],
            options={
                'db_table': 'ingredients_recette',
            },
        ),
        migrations.CreateModel(
            name='RepasTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_repas', models.CharField(choices=[('petit_dejeuner', 'Petit-déjeuner'), ('collation_matin', 'Collation matin'), ('dejeuner', 'Déjeuner'), ('collation_soir', 'Collation après-midi'), ('diner', 'Dîner')], max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to='core.planalimentaire')),
            ],
            options={
                'db_table': 'repas_templates',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AlimentRepas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('aliment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aliment')),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recette')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliments', to='core.repastemplate')),
            ],
            options={
                'db_table': 'aliments_repas',
            },
        ),
    ]
