# Generated by Django 6.0.5 on 2026-05-20 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationEau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantite_ml', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommation_eau', to='core.client')),
            ],
            options={
                'db_table': 'consommation_eau',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
