# Generated by Django 6.0.5 on 2026-05-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_consommationeau'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recettes/'),
        ),
    ]
