# Generated by Django 6.0.5 on 2026-05-21 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recette_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinReponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semaine', models.DateField()),
                ('energie', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sommeil', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('motivation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recuperation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.client')),
            ],
            options={
                'db_table': 'checkin_reponses',
                'ordering': ['-semaine'],
                'unique_together': {('client', 'semaine')},
            },
        ),
    ]
