# Generated by Django 6.0.5 on 2026-05-21 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_checkin_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('groupe_musculaire', models.CharField(choices=[('pectoraux', 'Pectoraux'), ('dorsaux', 'Dorsaux'), ('epaules', 'Épaules'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('abdominaux', 'Abdominaux'), ('quadriceps', 'Quadriceps'), ('ischio', 'Ischio-jambiers'), ('fessiers', 'Fessiers'), ('mollets', 'Mollets'), ('full_body', 'Full body'), ('cardio', 'Cardio')], max_length=20)),
                ('categorie', models.CharField(choices=[('force', 'Force'), ('cardio', 'Cardio'), ('mobilite', 'Mobilité'), ('gainage', 'Gainage')], default='force', max_length=20)),
                ('gif_url', models.URLField(blank=True)),
                ('gif_file', models.ImageField(blank=True, null=True, upload_to='exercices/')),
                ('est_personnalise', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_perso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercices',
                'ordering': ['groupe_musculaire', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceSeance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('series', models.PositiveSmallIntegerField(default=3)),
                ('repetitions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duree_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('repos_sec', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercice')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_planifies', to='core.seance')),
            ],
            options={
                'db_table': 'exercice_seances',
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
