# Generated by Django 6.0.5 on 2026-05-22 22:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message_image_alter_message_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeJour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semaine', models.PositiveSmallIntegerField(default=1)),
                ('jour', models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('7', 'Dimanche')], max_length=1)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='core.programme')),
            ],
            options={
                'db_table': 'programme_jours',
                'ordering': ['semaine', 'jour', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeJourExercice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_libre', models.CharField(blank=True, max_length=200)),
                ('series', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(blank=True, default='10', max_length=50)),
                ('repos_sec', models.PositiveSmallIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercice')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='core.programmejour')),
            ],
            options={
                'db_table': 'programme_jour_exercices',
                'ordering': ['ordre'],
            },
        ),
    ]
