# Generated by Django 6.0.5 on 2026-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_programmejour_programmejourexercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinreponse',
            name='alimentation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinreponse',
            name='confort_physique',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinreponse',
            name='humeur',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinreponse',
            name='hydratation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
