# Generated by Django 6.0.5 on 2026-05-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_push_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
