# Generated by Django 6.0.5 on 2026-05-27 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recette_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes', to=settings.AUTH_USER_MODEL),
        ),
    ]
