# Generated by Django 6.0.5 on 2026-05-27 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_recette_coach_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='core.recette'),
        ),
    ]
