# Generated by Django 6.0.5 on 2026-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_recette_original_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
