# Generated by Django 6.0.5 on 2026-05-28 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='reservation_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='reservation_duree_min',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='reservation_horizon_j',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='reservation_preavis_h',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('absences', 'Absences'), ('inactivite', 'Inactivité'), ('facture_retard', 'Facture retard'), ('fin_programme', 'Fin programme'), ('objectif_atteint', 'Objectif atteint'), ('nouvelle_mesure', 'Nouvelle mesure'), ('nouvelle_reservation', 'Nouvelle réservation')], default='absences', max_length=20),
        ),
        migrations.CreateModel(
            name='DisponibiliteCoach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disponibilites_coach',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionDisponibilite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('ferme', 'Fermé'), ('ouvert', 'Ouvert')], default='ferme', max_length=10)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions_dispo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exceptions_dispo',
                'ordering': ['date'],
            },
        ),
    ]
