# Generated by Django 6.0.5 on 2026-05-28 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_coachprofile_reservation_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_calendar_tokens',
            },
        ),
    ]
