# Generated by Django 6.0.5 on 2026-05-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seance_google_event_id_googlecalendartoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='gcal_block_allday',
            field=models.BooleanField(default=True, help_text="Bloquer les events all-day Google même marqués 'Disponible'"),
        ),
    ]
