# Generated by Django 6.0.5 on 2026-05-28 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_coachprofile_gcal_block_allday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icone', models.CharField(default='🏆', max_length=8)),
                ('categorie', models.CharField(choices=[('assiduite', 'Assiduité'), ('regularite', 'Régularité'), ('suivi', 'Suivi'), ('nutrition', 'Nutrition'), ('objectifs', 'Objectifs'), ('special', 'Spéciaux')], max_length=20)),
                ('condition', models.JSONField(default=dict)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ClientBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obtenu_le', models.DateTimeField(auto_now_add=True)),
                ('vu', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='core.badge')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.client')),
            ],
            options={
                'db_table': 'client_badges',
                'ordering': ['-obtenu_le'],
                'unique_together': {('client', 'badge')},
            },
        ),
    ]
