# Generated by Django 6.0.5 on 2026-05-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_seed_badges_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
