# Generated by Django 6.0.5 on 2026-06-01 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_recette_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('question', 'Question')], max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Mineur'), ('medium', 'Moyen'), ('high', 'Critique')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('rejected', 'Rejeté')], default='open', max_length=15)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
