# Generated by Django 6.0.5 on 2026-06-02 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='ia_generations_count_mois',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='ia_quota_mensuel',
            field=models.PositiveSmallIntegerField(default=10, help_text='Générations IA autorisées par mois'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='ia_quota_reset_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IACache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(choices=[('plan', 'Plan alimentaire'), ('programme', 'Programme entraînement')], max_length=20)),
                ('params_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ia_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach', 'endpoint', 'params_hash', '-created_at'], name='ia_cache_coach_i_cd29e2_idx')],
            },
        ),
    ]
