# Generated by Django 6.0.5 on 2026-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_coachprofile_ia_generations_count_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete : purge définitive 30 jours après cette date', null=True),
        ),
    ]
