# Generated by Django 6.0.5 on 2026-06-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_client_facturation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('absences', 'Absences'), ('inactivite', 'Inactivité'), ('facture_retard', 'Facture retard'), ('facture_mensuelle_manquante', 'Facture mensuelle manquante'), ('fin_programme', 'Fin programme'), ('objectif_atteint', 'Objectif atteint'), ('nouvelle_mesure', 'Nouvelle mesure'), ('nouvelle_reservation', 'Nouvelle réservation')], default='absences', max_length=30),
        ),
    ]
