# Generated by Django 6.0.5 on 2026-06-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_alerte_type_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='source',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('openfoodfacts', 'Open Food Facts')], default='manuel', max_length=20),
        ),
        migrations.AddField(
            model_name='aliment',
            name='source_id',
            field=models.CharField(blank=True, default='', help_text='Code-barres OFF si source = openfoodfacts', max_length=50),
        ),
        migrations.AddIndex(
            model_name='aliment',
            index=models.Index(fields=['source', 'source_id'], name='aliments_source_e98aa7_idx'),
        ),
    ]
